name: eudoria
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter 
  intl: ^0.17.0


  # Dependencies required by services.
  path_provider: ^2.0.11
  url_launcher: ^6.1.7

  # Dependencies required to record observations.
  textfield_tags: ^2.0.2
  location: ^4.4.0
  numberpicker: ^2.1.1
  fl_chart: ^0.55.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/eudoria.json
